### ISSUE TITLE
step09, where is "/pickles/all_sequences_with_NN_prop_helicity.pkl" from

### ISSUE THREAD

**Issue by rocke2020** [reymond-group/MLpeptide#2]
Dear Alice and reymond-group,

thanks for very much for your share of codes.
I am trying to reproduce your codes, in the start of '09-Property-analysis.ipynb',
df_all_nohem = pd.read_pickle(folder +"/pickles/all_sequences_with_NN_prop_helicity.pkl")
But I checked all your 13 ipynb, there is not another "all_sequences_with_NN_prop_helicity.pkl" avaible.
Could you review your codes to check this issues?
thanks a lot in advance!

Rocks Dong

**Comment by mehradans92** [comment]
same problem with `DAASP_RNN_dataset_with_hemolysis.plk`. Could you please share those as well?

**Comment by rocke2020** [comment]
It is normal to unseen this file. I think this file is the author's final results.
